config/routes.rb
Rails.application.routes.draw do
  get 'items/create'

  get 'users/show'

  devise_for :users

  resources :users, only: [:show] do
  	resources :items, only: [:create, :destroy]

  end

  root to:'users#show'

  get 'welcome/index'

  get 'welcome/about'

  root to:'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
   
  def create
  	@item = Item.new(item_params)
  	@item.user = current_user
    
    if @item.save
      flash[:notice] = "item saved successfully."
      redirect_to current_user
    else
      flash[:error] = "item failed to save."
      redirect_to current_user
    end
  end

  def destroy
    @item = current_user.items.find(params[:id])
    if @item.destroy
      flash[:notice] = "Item removed"
    else
      flash[:alert] = "Oops.. something went wrong.  try again."
    end

    respond_to do |format|
      format.html
      format.js 
    end 
  end

  private

  def item_params
  	params.require(:item).permit(:name)
  end  	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  
  def show
      @email = current_user.email
      @sign_in = current_user.last_sign_in_at
      @items = current_user.items
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [user, item] do |f| %>

	<div class="form-group">
		<%= f.text_field :name, class: 'form-control', placeholder: "Enter name of to do item" %>
	</div>
	<div class="form-group">
		<%= f.submit "Save", class: 'btn btn-success' %>
	</div>

<% end %>

app/views/items/_item.html.erb
<tbody>
  <%= content_tag :tr, class: "item", id: "item-#{item.id}" do %>
    <td>
    	<%= item.name %>
    </td>
    <td> (item expires in: <%= distance_of_time_in_words(item.created_at + 7.days, Date.today) %> on <%=item.created_at + 7.days %>) </td>
    <td><%= link_to "", [current_user, item], method: :delete, class: 'glyphicon glyphicon-ok', remote: true %></td>
  <% end %>
</tbody>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-<%= @item.id %>').fadeOut(1300);
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vera</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

<body>
    <div class="container">
        <ul class="nav nav-tabs">
          <li><%= link_to "Home", welcome_index_path %></li>
          <li><%= link_to "About", welcome_about_path %></li>
          <% if user_signed_in? %>
            <li>
              <li class="pull-right"><%= link_to(current_user.email, edit_user_registration_path)%></li>
              <li class="pull-right"><%= link_to('Sign Out', destroy_user_session_path, method: :delete) %>        
            </li>
          <% else %>
            <li>
              <li class="pull-right"><%= link_to('Sign In', new_user_session_path)  %>  
            </li>
          <% end %>
        </ul>
        <div>
      <% if flash[:notice] %>
        <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
        </div>
        <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
        </div>
        <% elsif flash[:alert] %>
        <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
        </div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<h1>Welcome <%= @current_user.email %></h1>

<div class="row">
  <div class="col-md-6">
    <p>How are you  doing today <%= @current_user.email %> doing today?</p>
  </div>
    <%= render 'items/form', item: Item.new, user: @current_user %>
</div>

<div class="row">
  <div class="list- col-md-8 pull-left">
    <h3 class="media-heading">
      <div class="media-body">
        <table class="table">
          <thead>
            <tr>
              <th>To Do Items</th>
            </tr>
          </thead>
          <tbody>
            <tr class='js-items'>
              <%= render @items %>
            </tr>
          </tbody>
        </table>
      </div>
    </h3>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome To Vera</h1>
<p>An application that allows users to create self-destructing to-do lists.</p>